services:
  - type: web
    name: metro_dz
    env: docker
    plan: free
    healthCheckPath: /api/health
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql