services:
  - type: web
    name: metro_dz
    env: docker
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 8080
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql